import type { PlannerLayoutConfig, PlannerTemplate, ColumnLayout } from "@openframe/shared";

export const DEFAULT_PLANNER_CONFIG: PlannerLayoutConfig = {
  gridColumns: 12,
  gridRows: 12,
  pageSize: "remarkable2",
  orientation: "portrait",
  widgets: [],
  backgroundColor: "#ffffff",
};

export const PLANNER_TEMPLATES: Record<string, PlannerTemplate> = {
  "daily-agenda": {
    id: "daily-agenda",
    name: "Daily Planner",
    description: "Comprehensive daily planner with schedule, tasks, and reflection",
    thumbnail: "/templates/daily-agenda.png",
    config: {
      gridColumns: 12,
      gridRows: 12,
      pageSize: "remarkable2",
      orientation: "portrait",
      backgroundColor: "#ffffff",
      widgets: [
        // Left column - Date and Tasks
        {
          id: "text-date",
          type: "text",
          x: 0,
          y: 0,
          width: 4,
          height: 1,
          config: { text: "{{date:D dddd}}", fontSize: "lg", align: "center" },
        },
        {
          id: "calendar-week-mini",
          type: "calendar-week",
          x: 0,
          y: 1,
          width: 4,
          height: 1,
          config: { showDayNames: true, compact: true },
        },
        {
          id: "tasks-top3",
          type: "tasks",
          x: 0,
          y: 2,
          width: 4,
          height: 2,
          config: { maxItems: 3, title: "Top 3 Tasks" },
        },
        {
          id: "tasks-todo",
          type: "tasks",
          x: 0,
          y: 4,
          width: 4,
          height: 3,
          config: { maxItems: 6, title: "To-Do List" },
        },
        {
          id: "tasks-personal",
          type: "tasks",
          x: 0,
          y: 7,
          width: 4,
          height: 3,
          config: { maxItems: 5, title: "Personal" },
        },
        {
          id: "habits-tracker",
          type: "habits",
          x: 0,
          y: 10,
          width: 4,
          height: 2,
          config: { habits: ["Water", "Exercise", "Sleep"], title: "Daily Habits" },
        },
        // Center column - Schedule
        {
          id: "text-schedule",
          type: "text",
          x: 4,
          y: 0,
          width: 4,
          height: 1,
          config: { text: "Schedule", fontSize: "base", align: "center" },
        },
        {
          id: "calendar-day-schedule",
          type: "calendar-day",
          x: 4,
          y: 1,
          width: 4,
          height: 11,
          config: { showTime: true, startHour: 7, endHour: 21 },
        },
        // Right column - Gratitude & Reflection
        {
          id: "text-gratitude-header",
          type: "text",
          x: 8,
          y: 0,
          width: 4,
          height: 1,
          config: { text: "Daily Gratitude", fontSize: "base", align: "center" },
        },
        {
          id: "notes-gratitude",
          type: "notes",
          x: 8,
          y: 1,
          width: 4,
          height: 2,
          config: { title: "Gratitude", lineStyle: "ruled" },
        },
        {
          id: "notes-affirmation",
          type: "notes",
          x: 8,
          y: 3,
          width: 4,
          height: 2,
          config: { title: "Affirmation", lineStyle: "ruled" },
        },
        {
          id: "notes-wins",
          type: "notes",
          x: 8,
          y: 5,
          width: 4,
          height: 3,
          config: { title: "Wins of the Day", lineStyle: "ruled" },
        },
        {
          id: "notes-general",
          type: "notes",
          x: 8,
          y: 8,
          width: 4,
          height: 4,
          config: { title: "Notes", lineStyle: "ruled" },
        },
      ],
    },
  },
  "adhd-planner": {
    id: "adhd-planner",
    name: "ADHD Daily Planner",
    description: "3-column focus planner with updates, priorities, and schedule",
    thumbnail: "/templates/adhd-planner.png",
    config: {
      gridColumns: 12,
      gridRows: 12,
      pageSize: "remarkable2",
      orientation: "portrait",
      backgroundColor: "#ffffff",
      widgets: [
        // Header - Date banner and meta
        {
          id: "text-date",
          type: "text",
          x: 0,
          y: 0,
          width: 4,
          height: 1,
          config: { text: "{{date:D dddd}}", fontSize: "lg", align: "center" },
        },
        {
          id: "text-week-month",
          type: "text",
          x: 4,
          y: 0,
          width: 8,
          height: 1,
          config: { text: "{{date:MMMM YYYY}}", fontSize: "sm", align: "right" },
        },
        // Column 1 (Left): Updates + Brain Dump
        {
          id: "news-updates",
          type: "news-headlines",
          x: 0,
          y: 1,
          width: 4,
          height: 7,
          config: { maxItems: 5, title: "Updates" },
        },
        {
          id: "notes-brain-dump",
          type: "notes",
          x: 0,
          y: 8,
          width: 4,
          height: 4,
          config: { title: "Brain Dump", lineStyle: "dotted" },
        },
        // Column 2 (Center): Priorities + Reward + Less Important + Trackers
        {
          id: "tasks-focus",
          type: "tasks",
          x: 4,
          y: 1,
          width: 4,
          height: 2,
          config: { maxItems: 3, title: "Focus / Top Priorities" },
        },
        {
          id: "notes-reward",
          type: "notes",
          x: 4,
          y: 3,
          width: 4,
          height: 1,
          config: { title: "My Reward", lineStyle: "ruled" },
        },
        {
          id: "tasks-less-important",
          type: "tasks",
          x: 4,
          y: 4,
          width: 4,
          height: 3,
          config: { maxItems: 5, title: "Less Important" },
        },
        {
          id: "habits-tracker",
          type: "habits",
          x: 4,
          y: 7,
          width: 4,
          height: 5,
          config: { habits: ["Hydration", "Nutrition", "Movement", "Sleep", "Mindfulness"], title: "Self-Care" },
        },
        // Column 3 (Right): Schedule
        {
          id: "calendar-day-schedule",
          type: "calendar-day",
          x: 8,
          y: 1,
          width: 4,
          height: 11,
          config: { showTime: true, startHour: 7, endHour: 21 },
        },
      ],
    },
  },
  "weekly-planner": {
    id: "weekly-planner",
    name: "Weekly Planner",
    description: "7-day week view with tasks sidebar",
    thumbnail: "/templates/weekly-planner.png",
    config: {
      gridColumns: 12,
      gridRows: 8,
      pageSize: "remarkable2",
      orientation: "landscape",
      backgroundColor: "#ffffff",
      widgets: [
        {
          id: "text-week",
          type: "text",
          x: 0,
          y: 0,
          width: 12,
          height: 1,
          config: { text: "Week of {{date:MMMM D, YYYY}}", fontSize: "xl", fontWeight: "bold", textAlign: "center" },
        },
        {
          id: "calendar-week-main",
          type: "calendar-week",
          x: 0,
          y: 1,
          width: 10,
          height: 6,
          config: { showDayNames: true, showDates: true, compactEvents: true },
        },
        {
          id: "tasks-sidebar",
          type: "tasks",
          x: 10,
          y: 1,
          width: 2,
          height: 6,
          config: { maxItems: 15, showCheckboxes: true, showDueDate: false },
        },
        {
          id: "notes-footer",
          type: "notes",
          x: 0,
          y: 7,
          width: 12,
          height: 1,
          config: { lineSpacing: 20, showTitle: false, lineStyle: "ruled" },
        },
      ],
    },
  },
  "information-dashboard": {
    id: "information-dashboard",
    name: "Information Dashboard",
    description: "News, weather, upcoming events, and tasks",
    thumbnail: "/templates/info-dashboard.png",
    config: {
      gridColumns: 12,
      gridRows: 8,
      pageSize: "remarkable2",
      orientation: "portrait",
      backgroundColor: "#ffffff",
      widgets: [
        {
          id: "text-title",
          type: "text",
          x: 0,
          y: 0,
          width: 12,
          height: 1,
          config: { text: "{{date:dddd, MMMM D}}", fontSize: "xl", fontWeight: "bold", textAlign: "center" },
        },
        {
          id: "weather-top",
          type: "weather",
          x: 0,
          y: 1,
          width: 6,
          height: 2,
          config: { showIcon: true, showHighLow: true, forecastDays: 3 },
        },
        {
          id: "calendar-day-events",
          type: "calendar-day",
          x: 6,
          y: 1,
          width: 6,
          height: 3,
          config: { showTimeSlots: false, showLocation: true },
        },
        {
          id: "divider-1",
          type: "divider",
          x: 0,
          y: 3,
          width: 6,
          height: 1,
          config: { orientation: "horizontal", style: "solid" },
        },
        {
          id: "news-left",
          type: "news-headlines",
          x: 0,
          y: 4,
          width: 6,
          height: 4,
          config: { maxItems: 8, showSource: true },
        },
        {
          id: "tasks-right",
          type: "tasks",
          x: 6,
          y: 4,
          width: 6,
          height: 4,
          config: { maxItems: 10, showCheckboxes: true },
        },
      ],
    },
  },
  "habit-tracker": {
    id: "habit-tracker",
    name: "Habit Tracker",
    description: "Monthly habit tracking grid with notes",
    thumbnail: "/templates/habit-tracker.png",
    config: {
      gridColumns: 12,
      gridRows: 8,
      pageSize: "remarkable2",
      orientation: "landscape",
      backgroundColor: "#ffffff",
      widgets: [
        {
          id: "text-month",
          type: "text",
          x: 0,
          y: 0,
          width: 12,
          height: 1,
          config: { text: "{{date:MMMM YYYY}} Habits", fontSize: "xl", fontWeight: "bold", textAlign: "center" },
        },
        {
          id: "habits-grid",
          type: "habits",
          x: 0,
          y: 1,
          width: 12,
          height: 5,
          config: {
            habits: ["Exercise", "Read", "Meditate", "Drink Water", "Journal"],
            showDates: true,
            checkboxStyle: "circle",
          },
        },
        {
          id: "divider-bottom",
          type: "divider",
          x: 0,
          y: 6,
          width: 12,
          height: 1,
          config: { orientation: "horizontal", style: "dashed" },
        },
        {
          id: "notes-bottom",
          type: "notes",
          x: 0,
          y: 7,
          width: 12,
          height: 1,
          config: { lineSpacing: 20, showTitle: false, lineStyle: "ruled" },
        },
      ],
    },
  },
  "month-at-glance": {
    id: "month-at-glance",
    name: "Month at a Glance",
    description: "Full month calendar with mini task list",
    thumbnail: "/templates/month-glance.png",
    config: {
      gridColumns: 12,
      gridRows: 8,
      pageSize: "remarkable2",
      orientation: "landscape",
      backgroundColor: "#ffffff",
      widgets: [
        {
          id: "text-month",
          type: "text",
          x: 0,
          y: 0,
          width: 12,
          height: 1,
          config: { text: "{{date:MMMM YYYY}}", fontSize: "2xl", fontWeight: "bold", textAlign: "center" },
        },
        {
          id: "calendar-month-main",
          type: "calendar-month",
          x: 0,
          y: 1,
          width: 9,
          height: 7,
          config: { showWeekNumbers: true, highlightToday: true, showEventDots: true },
        },
        {
          id: "tasks-sidebar",
          type: "tasks",
          x: 9,
          y: 1,
          width: 3,
          height: 4,
          config: { maxItems: 10, showCheckboxes: true, showDueDate: true },
        },
        {
          id: "notes-sidebar",
          type: "notes",
          x: 9,
          y: 5,
          width: 3,
          height: 3,
          config: { lineSpacing: 18, title: "Notes", lineStyle: "ruled" },
        },
      ],
    },
  },
  blank: {
    id: "blank",
    name: "Blank Canvas",
    description: "Start from scratch with an empty layout",
    thumbnail: "/templates/blank.png",
    config: {
      gridColumns: 12,
      gridRows: 8,
      pageSize: "remarkable2",
      orientation: "portrait",
      backgroundColor: "#ffffff",
      widgets: [],
    },
  },
  "adhd-live-planner": {
    id: "adhd-live-planner",
    name: "ADHD Live Planner",
    description: "Interactive 3-column planner with resizable sections - edit directly in the styled view",
    thumbnail: "/templates/adhd-live.png",
    config: {
      gridColumns: 12,
      gridRows: 12,
      pageSize: "remarkable2",
      orientation: "portrait",
      backgroundColor: "#f5f2ed",
      layoutMode: "columns",
      widgets: [
        // Header text widget
        {
          id: "header-text",
          type: "text",
          x: 0,
          y: 0,
          width: 12,
          height: 1,
          config: { text: "{{date:D dddd}}", fontSize: "lg", fontWeight: "bold" },
        },
        // Updates widget (left column)
        {
          id: "updates",
          type: "news-headlines",
          x: 0,
          y: 1,
          width: 4,
          height: 7,
          config: { maxItems: 5, title: "Updates" },
        },
        // Focus/Priorities widget (center column top)
        {
          id: "priorities",
          type: "tasks",
          x: 4,
          y: 1,
          width: 4,
          height: 3,
          config: { maxItems: 3, title: "Focus / Top Priorities" },
        },
        // Reward widget (center column)
        {
          id: "reward",
          type: "notes",
          x: 4,
          y: 4,
          width: 4,
          height: 1,
          config: { title: "My Reward", lineStyle: "ruled" },
        },
        // Less Important tasks (center column)
        {
          id: "less-important",
          type: "tasks",
          x: 4,
          y: 5,
          width: 4,
          height: 3,
          config: { maxItems: 5, title: "Less Important" },
        },
        // Schedule widget (right column)
        {
          id: "schedule",
          type: "calendar-day",
          x: 8,
          y: 1,
          width: 4,
          height: 7,
          config: { showTime: true, startHour: 7, endHour: 21, title: "Schedule" },
        },
        // Brain Dump widget (bottom left)
        {
          id: "brain-dump",
          type: "notes",
          x: 0,
          y: 8,
          width: 6,
          height: 4,
          config: { title: "Brain Dump", lineStyle: "dotted" },
        },
        // Self-Care / Habits widget (bottom right)
        {
          id: "self-care",
          type: "habits",
          x: 6,
          y: 8,
          width: 6,
          height: 4,
          config: { habits: ["Hydration", "Nutrition", "Movement", "Sleep", "Mindfulness"], title: "Self-Care", columns: 2, showLabels: true },
        },
      ],
      columns: {
        sections: [
          {
            id: "main",
            direction: "vertical",
            children: [
              // Header row
              { id: "header", type: "widget", flex: 0.08, widgetId: "header-text" },
              // Body - 3 columns
              {
                id: "body",
                type: "section",
                flex: 0.72,
                section: {
                  id: "body-section",
                  direction: "horizontal",
                  children: [
                    // Left column - Updates
                    { id: "col1", type: "widget", flex: 1, widgetId: "updates" },
                    // Center column - nested vertical section
                    {
                      id: "col2",
                      type: "section",
                      flex: 1,
                      section: {
                        id: "col2-section",
                        direction: "vertical",
                        children: [
                          { id: "col2-top", type: "widget", flex: 1.2, widgetId: "priorities" },
                          { id: "col2-reward", type: "widget", flex: 0.4, widgetId: "reward" },
                          { id: "col2-tasks", type: "widget", flex: 1.2, widgetId: "less-important" },
                        ],
                      },
                    },
                    // Right column - Schedule
                    { id: "col3", type: "widget", flex: 1, widgetId: "schedule" },
                  ],
                },
              },
              // Bottom row - 2 sections
              {
                id: "bottom",
                type: "section",
                flex: 0.2,
                section: {
                  id: "bottom-section",
                  direction: "horizontal",
                  children: [
                    { id: "bottom-left", type: "widget", flex: 1, widgetId: "brain-dump" },
                    { id: "bottom-right", type: "widget", flex: 1, widgetId: "self-care" },
                  ],
                },
              },
            ],
          },
        ],
      } as ColumnLayout,
    },
  },
};

export function getTemplateById(id: string): PlannerTemplate | undefined {
  return PLANNER_TEMPLATES[id];
}

export function getAllTemplates(): PlannerTemplate[] {
  return Object.values(PLANNER_TEMPLATES);
}
