name: OpenFrame
options:
  bundleIdPrefix: us.openframe
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "8"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGN_STYLE: Automatic

targets:
  OpenFrame:
    type: application
    platform: iOS
    sources:
      - path: OpenFrame
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: us.openframe.app
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: OpenFrame/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
    info:
      path: OpenFrame/Resources/Info.plist
    entitlements:
      path: OpenFrame/Resources/OpenFrame.entitlements
